name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: publish Hathor on version change
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Hathor/Hathor.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish Wallet on version change
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Hathor.Wallet/Hathor.Wallet.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
